import Header from "./_components/Header";
import Hero from "./_components/Hero";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div>
      {/* HEADER */}
      <Header/>
      <Hero/>
      {/* Hero Section */}
    </div>
  )
}

